name: CI/CD
run-name: ${{ github.actor }} is deploying the project 🚀

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, edited, reopened]

jobs:
  build:
    name: Testing and building
    strategy:
      matrix:
        node-version: [14.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install modules
        run: npm install

      - name: Linting Typescript
        run: npm run lint:ts

      - name: Linting SCSS
        run: npm run lint:scss

      - name: Unit testing
        run: npm run unit

      - name: Build production project
        run: npm run build:prod

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy
    needs: build
    strategy:
      matrix:
        node-version: [14.x]
        os: [ ubuntu-latest, windows-latest ]
      runs-on: ${{ matrix.os }}
    continue-on-error: true
    env:
      GH-SECRET: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ env.GH-SECRET }}
          publish_dir: ./build
